### ISSUE TITLE
Сервис не работает в режиме ожидания

### ISSUE THREAD

**Issue by ATumbler** [firebase/firebase-jobdispatcher-android#98] opened 2017-03-05 02:17 UTC
Я использую связку FJD + Volley для периодического подключения к серверу. Уведомления не приходят на заблокированном экране

Сервис:

public class NotificationJobService extends JobService
{
	SharedPreferences pref;
	SharedPreferences.Editor editor;

    @Override
    public boolean onStartJob(JobParameters job)
	{
        pref = getApplicationContext().getSharedPreferences("settings", Context.MODE_PRIVATE);
        editor = pref.edit();
		String url = SomeClass.BASE_URL;
		
		Response.Listener<String> responseSuccess = new Response.Listener<String>(){
			@Override
			public void onResponse(String response)
			{
				if(!response.endsWith("ь")) {
					int serverId = Integer.parseInt(response);
                    int prefId = getLastPrefId();
                    if (prefId == 0) prefId = serverId;
                    if (serverId > prefId)
                    {
                        showNotification();
                    }
                        setLastPrefId(serverId);
                }
			}
		};
		
		Response.ErrorListener responseFailed = new Response.ErrorListener(){

			@Override
			public void onErrorResponse(VolleyError error)
			{
				
			}
		};
		
		StringRequest request = new StringRequest(Request.Method.POST, url, responseSuccess, responseFailed){
			@Override
            protected Map<String, String> getParams()
            {
                Map<String, String> params = new HashMap<String, String>();
                params.put("login", pref.getString("address", ""));
				params.put("password", pref.getString("key", ""));
				params.put("get", "lastid");
                return params;
            }
		};
		VolleyApplication.getInstance().getRequestQueue().add(request);
		return false;
    }

    @Override
    public boolean onStopJob(JobParameters job)
	{
        return true;
    }

	public int getLastPrefId()
	{ return pref.getInt("lastid", 0); }

	public void setLastPrefId(int pref)
	{
		editor.putInt("lastid", pref);
		editor.commit();
	}

	public void showNotification()
	{
		NotificationCompat.Builder mBuilder = new NotificationCompat.Builder(this)
			.setSmallIcon(R.drawable.ic_launcher)
			.setContentTitle("У вас новая заявка")
			.setContentText("Открыть приложение")
			.setSound(RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION))
			.setAutoCancel(true);
		Intent intent = new Intent(this, MainActivity.class);
		PendingIntent pi = PendingIntent.getActivity(this, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
		mBuilder.setContentIntent(pi);
		NotificationManager mNotificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
		mNotificationManager.notify(0, mBuilder.build());
	}
}

Создание Job и запуск

FirebaseJobDispatcher dispatcher = new FirebaseJobDispatcher(new GooglePlayDriver(context));
		Job myJob = dispatcher.newJobBuilder()
            .setService(NotificationJobService.class)
            .setTag("request")
            .setRecurring(true)
            .setLifetime(Lifetime.FOREVER)
            .setTrigger(Trigger.executionWindow(0, 60))
            .setReplaceCurrent(false)
            .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
            .setConstraints(Constraint.ON_ANY_NETWORK) 
            .build();

		dispatcher.schedule(myJob);

Что я делаю не так?

**Comment by stepango** [comment] 2017-03-07 08:47
Заводишь issue на русском языке ¯\_(ツ)_/¯

**Comment by highel** [comment] 2017-06-09 16:39
if(!response.endsWith("ь")) maybe the problem is in the soft sign?

**Comment by unEgor** [comment] 2017-06-09 20:21
It does not look like the issue in FDJ. So I'm closing it.

JFYI Android N enforce 15 minutes minimum interval for periodic jobs.

**Closed by unEgor** 2017-06-09 20:21 UTC
