### ISSUE TITLE
Any Update of this library for targetting API 26 or more?

### ISSUE THREAD

**Issue by deathstroke007** [firebase/firebase-jobdispatcher-android#281] opened 2019-02-01 20:28 UTC
Currently this library targetSDK is 26 and Google play console giving me warning about this. what to do?
Any help?
<img width="398" alt="jobdispatcher" src="https://user-images.githubusercontent.com/14835243/52148615-4b2e9180-2690-11e9-8656-bc8859cddae0.PNG">

Why am i getting the target SDK 25 when i am using 0.8.5 and i saw your library has target 27? I am not able to upload the app to the playstore?

**Comment by SamratPyaraka** [comment] 2019-04-08 06:59
> Currently this library targetSDK is 26 and Google play console giving me warning about this. what to do?
> Any help?
> <img alt="jobdispatcher" width="398" src="https://user-images.githubusercontent.com/14835243/52148615-4b2e9180-2690-11e9-8656-bc8859cddae0.PNG">
> 
> Why am i getting the target SDK 25 when i am using 0.8.5 and i saw your library has target 27? I am not able to upload the app to the playstore?

@deathstroke007 please check the <uses-sdk> tag, in that you have mentioned "android:targetSdkVerion=25". Update that to 26, that might solve your problem.

**Comment by toddshansen** [comment] 2019-05-06 20:13
closing this as I think @SamratPyaraka  is right about the cause here

**Closed by toddshansen** 2019-05-06 20:13 UTC
