### ISSUE TITLE
Job not reschedule after device reboot

### ISSUE THREAD

**Issue by nikthakkar** [firebase/firebase-jobdispatcher-android#101] opened 2017-03-30 05:22 UTC
I'm using the following configuration to build the job.
 ```
Job job = dispatcher.newJobBuilder()
                .setTag(LocationSyncService.TAG)
                .setLifetime(Lifetime.FOREVER)
                .setRecurring(true)
                .setReplaceCurrent(true)
                .setService(LocationSyncService.class)
                .setTrigger(Trigger.executionWindow((int) TimeUnit.MINUTES.toSeconds(1), (int) TimeUnit.MINUTES.toSeconds(2)))
                .setRetryStrategy(RetryStrategy.DEFAULT_EXPONENTIAL)
                .setConstraints(Constraint.ON_ANY_NETWORK)
                .build();
        dispatcher.mustSchedule(job);
```
It works fine until the device is rebooted. I'm running Nougat 7.1.1 for testing. If I open the app after device reboot, the task is scheduled and running successfully.
Please let me know if something is amiss. 
Any help would be greatly appreciated.

**Comment by FabianTerhorst** [comment] 2017-03-31 13:16
Why not just register an on boot complete receiver and reschedule the jobs?

**Comment by nikthakkar** [comment] 2017-03-31 15:22
The problem is my app is not receiving the BOOT_COMPLETE intent even though I have registered the receiver in mainfest. Otherwise I would have followed the same approach as suggested by you.
Thanks for the help.

**Comment by FabianTerhorst** [comment] 2017-03-31 18:03
you added the ```<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />``` permission?

**Comment by nikthakkar** [comment] 2017-03-31 18:06
Yes. :). I switched to evernote's android-job library and it seems to work fine. Though I have to settle for 15min window between job execution. Hopefully you guys will fix this soon as I'm already using firebase auth and database and this would have completed the fire base stack.. :)

**Comment by yishai-glide** [comment] 2017-04-12 07:11
@nikthakkar evernote library merges the `RECEIVE_BOOT_COMPLETED` permission from the library manifest

I kinda thought that I would be able to avoid declaring new permissions for this and use the gms built in functions instead...

**Comment by mikevandre** [comment] 2017-06-15 20:27
I am experiencing this same problem. I cannot get my job to start up after reboot even after using LIfetime.Forever and adding the RECEIVE_BOOT_COMPLETED permission

**Comment by xanderblinov** [comment] 2017-06-20 15:27
Should I perform rescheduling manual or adding RECEIVE_BOOT_COMPLETED permission to manifest will fix this issue? @FabianTerhorst

**Comment by dhirenpratap** [comment] 2017-06-22 06:35
Same issue. I am not able to get the job working in both the scenarios:
1.  if app is closed 
2. post reboot

**Comment by dhirenpratap** [comment] 2017-06-22 06:39
I dumped log and I found this:

06-22 12:07:44.116  2570  3348 E NetworkScheduler.TED: Couldn't start service: Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY cmp=co.wepact.rupie/com.firebase.jobdispatcher.GooglePlayReceiver (has extras) }

**Comment by ogeidix** [comment] 2017-07-02 15:16
Everybody who is affected by this problem, could you check the following command while your app is closed (after a reboot or after swiping)

`adb shell dumpsys package MY-PACKAGE | grep stopped`

if you can read `stopped=true` it means that the manufacturer of your device implemented a non standard behavior consisting in "force-stopping" applications when they are swiped.

force-stopping is very similar to disabling the app until the user opens it again.
while the app is in that state many android behaviors will not work (broadcasts, alarms..)

If this is the root cause of behavior you are seeing you should contact the manufacturer and request that they fix the device by removing this non-standard behavior

**Comment by a-tolstykh** [comment] 2017-08-07 14:04
@ogeidix I'm also experiencing this issue.

I've executed the command you suggested and the output contains `stopped=false`, and a job is not restored:
```
$ adb shell dumpsys package <package> | grep stopped
    User 0:  installed=true hidden=false stopped=false notLaunched=false enabled=0
```

**Comment by YaasinAJDI** [comment] 2017-08-29 14:03
Any fix for this yet??

**Comment by GregorioDiStefano** [comment] 2017-09-17 15:15
Same issue here, will try to debug..

**Comment by tulburg** [comment] 2017-09-25 04:45
this just killed a product for me. its device specific and mostly not the main manufactural. Please fix!

full info here: http://edit.sumimasen.com/naosu.html?site=stackoverflow&id=45066610

**Comment by ThanosFisherman** [comment] 2017-10-20 21:53
Experiencing the same issue here not just after device reboot but also in standby. 

When I leave my app running in the background I get the following response from the suggested command:

```
 User 0:  installed=true hidden=false **stopped=false** notLaunched=false enabled=0
 User 999:  installed=false hidden=false **stopped=true** notLaunched=true enabled=0
```

Now when I select the "clear all" from overview screen and then execute this command again I get this:

```
User 0:  installed=true hidden=false **stopped=true** notLaunched=false enabled=0
User 999:  installed=false hidden=false **stopped=true** notLaunched=true enabled=0
```

My device is Xiaomi RedMi Pro running android 6.0

**Comment by dylan-chong** [comment] 2018-01-10 21:06
I also having a problem where, after a reboot on a oneplus, the job is scheduled according to `adb shell dumpsys activity service GcmService` but the service does not start `01-11 10:01:16.915 9260-11668/? E/NetworkScheduler.TED: Couldn't start service: Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY cmp=com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver (has extras) }`

I can see this in the logcat (some of it may not be relevant to this library:

```
01-11 10:01:16.889 9296-9296/? E/BroadcastReceiver: BroadcastReceiver trying to return result during a non-ordered broadcast
                                                    java.lang.RuntimeException: BroadcastReceiver trying to return result during a non-ordered broadcast
                                                        at android.content.BroadcastReceiver.checkSynchronousHint(BroadcastReceiver.java:682)
                                                        at android.content.BroadcastReceiver.setResult(BroadcastReceiver.java:557)
                                                        at com.google.android.gcm.GCMBroadcastReceiver.onReceive(GCMBroadcastReceiver.java:61)
                                                        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3410)
                                                        at android.app.ActivityThread.-wrap17(Unknown Source:0)
                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1772)
                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                        at android.os.Looper.loop(Looper.java:164)
                                                        at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
01-11 10:01:16.891 7488-7999/? V/AlarmManager: Triggering alarm #0: 2 when =1209212 package =com.google.android.gms operation =*walarm*:com.google.android.location.ALARM_WAKEUP_BURST_COLLECTION_TRIGGER flags =0x0
01-11 10:01:16.891 7488-7999/? V/AlarmManager: Triggering alarm #1: 2 when =1252381 package =android operation = null listenTag =WifiConnectivityManager Schedule Periodic Scan Timer flags =0x8
01-11 10:01:16.891 7488-7999/? V/AlarmManager: Triggering alarm #2: 3 when =1280510 package =com.google.android.gms operation =*alarm*:com.google.android.gms/.lockbox.LockboxAlarmReceiver flags =0x0
01-11 10:01:16.891 7488-7999/? V/AlarmManager: Triggering alarm #3: 1 when =1515618000000 package =com.google.android.calendar operation =*alarm*:com.google.android.calendar.APPWIDGET_SCHEDULED_UPDATE flags =0x0
01-11 10:01:16.892 9296-19565/? I/SubscribedFeeds: Received message
01-11 10:01:16.910 7488-8628/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=com.google.android.calendar.APPWIDGET_SCHEDULED_UPDATE dat=content://com.android.calendar typ=vnd.android.data/update flg=0x14 (has extras) } to com.google.android.calendar/com.android.calendar.widget.CalendarAppWidgetProvider
01-11 10:01:16.915 9260-11668/? E/NetworkScheduler.TED: Couldn't start service: Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY cmp=com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver (has extras) }
01-11 10:01:16.916 9260-11705/? E/NetworkScheduler: Unknown result code received: 4
01-11 10:01:16.923 9260-18722/? E/NetworkScheduler.TED: Unable to bind to task service: ComponentInfo{com.atlassian.android.jira.core/com.firebase.jobdispatcher.GooglePlayReceiver}
01-11 10:01:16.925 7488-14577/? W/ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@bfa7b49
01-11 10:01:16.932 9260-11705/? E/NetworkScheduler: Unknown result code received: 4
```

**Comment by dylan-chong** [comment] 2018-01-10 21:20
I can confirm this error shows up in the logcat when to service tries to start (most of the above logs then are probably irrelevant):

```
01-11 10:18:16.983 9260-11668/? E/NetworkScheduler.TED: Couldn't start service: Intent { act=com.google.android.gms.gcm.ACTION_TASK_READY cmp=com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver (has extras) }
01-11 10:18:16.984 9260-17433/? E/NetworkScheduler: Unknown result code received: 4
```
I can tell that the service tried to start because of the scheduled time suddenly changing

```
    (finished) [com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver:on-device-boot,u0]
    (scheduled) com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="on-device-boot" trigger=window{start=0s,end=60s,earliest=-57s,latest=2s} requirements=[NET_ANY] attributes=[PERSISTED,RECURRING] scheduled=-57s last_run=N/A jid=N/A status=PENDING retries=6 client_lib=FIREBASE_JOB_DISPATCHER-1}
    (finished) [com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver:on-device-boot,u0]
    (scheduled) com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="on-device-boot" trigger=window{start=0s,end=60s,earliest=-58s,latest=1s} requirements=[NET_ANY] attributes=[PERSISTED,RECURRING] scheduled=-58s last_run=N/A jid=N/A status=PENDING retries=6 client_lib=FIREBASE_JOB_DISPATCHER-1}
    (finished) [com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver:on-device-boot,u0]
    (scheduled) com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="on-device-boot" trigger=window{start=0s,end=60s,earliest=-59s,latest=0s} requirements=[NET_ANY] attributes=[PERSISTED,RECURRING] scheduled=-59s last_run=N/A jid=N/A status=PENDING retries=6 client_lib=FIREBASE_JOB_DISPATCHER-1}
    (finished) [com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver:on-device-boot,u0]
    (scheduled) com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="on-device-boot" trigger=window{start=0s,end=60s,earliest=1919s,latest=1979s} requirements=[NET_ANY] attributes=[PERSISTED,RECURRING] scheduled=1919s last_run=N/A jid=N/A status=PENDING retries=7 client_lib=FIREBASE_JOB_DISPATCHER-1}
    (finished) [com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver:on-device-boot,u0]
    (scheduled) com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="on-device-boot" trigger=window{start=0s,end=60s,earliest=1918s,latest=1978s} requirements=[NET_ANY] attributes=[PERSISTED,RECURRING] scheduled=1918s last_run=N/A jid=N/A status=PENDING retries=7 client_lib=FIREBASE_JOB_DISPATCHER-1}
    (finished) [com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver:on-device-boot,u0]
    (scheduled) com.thundermaps.staging.main/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="on-device-boot"
```

**Comment by dylan-chong** [comment] 2018-01-10 21:23
I also get this

```
> adb shell dumpsys package com.thundermaps.staging.main | grep stopped
    User 0: ceDataInode=1991332 installed=true hidden=false suspended=false stopped=false notLaunched=false enabled=0 instant=false
    User 10: ceDataInode=0 installed=true hidden=false suspended=false stopped=true notLaunched=true enabled=0 instant=false
    User 11: ceDataInode=0 installed=true hidden=false suspended=false stopped=true notLaunched=true enabled=0 instant=false
```

`stopped=false` on the user zero is probably a good sign

**Comment by dylan-chong** [comment] 2018-01-16 01:46
@dhirenpratap looks like you had the same problem and error as me. Did you find anything in the last 6 months?

**Comment by eggcaker** [comment] 2018-02-02 11:03
same error here, job  cannot start after reboot

**Comment by shadowsheep1** [comment] 2018-07-24 09:39
Adding `<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />` solve the problem for me. No other action needed.

**Comment by samtstern** [comment] 2020-04-07 21:04
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.

**Closed by samtstern** 2020-04-07 21:04 UTC
