### ISSUE TITLE
GooglePlayDriver: doesn't reschedule Jobs after App is updated.

### ISSUE THREAD

**Issue by raphaelMediaMonk** [firebase/firebase-jobdispatcher-android#6] opened 2016-05-29 00:48 UTC
GooglePlayDriver doesn't reschedule Jobs after Google Play Services or the app is updated.

GooglePlayReceiver has check for that situation in [onStartCommand](https://github.com/firebase/firebase-jobdispatcher-android/blob/master/jobdispatcher/src/main/java/com/firebase/jobdispatcher/GooglePlayReceiver.java#L85-L87), but it doesn't handle this case correctly. All Jobs should be rescheduled.

To Reproduce issue:
1) create any recurring Job with Lifetime.FOREVER.
2) schedule the job.
3) install updated .apk or update Google Play Services.
4) Job won't be called no more.

**Comment by tomaszrykala** [comment] 2016-06-02 12:10
Confirmed. Any current workarounds?

**Comment by libhide** [comment] 2016-10-05 05:25
Hey! Is this still an issue? I want to use the library in production. I've got the library working like I want it too but reading this issue has got me worried.

**Comment by ciarand** [comment] 2016-10-06 00:22
Yes, this is still happening. We have an internal issue tracking this (the fix needs to happen in Google Play services), but the fix hasn't been launched yet.

For now, as a workaround, I recommend scheduling all your jobs sometime during your initialization phase with shouldReplaceCurrent set to false: https://github.com/firebase/firebase-jobdispatcher-android/blob/0.5.0/jobdispatcher/src/main/java/com/firebase/jobdispatcher/JobParameters.java#L82

**Comment by libhide** [comment] 2016-10-12 13:51
@ciarand Ah, damn. Thing is, in the app I'm working on, I schedule a recurring job (repeats everyday) which runs a service to fetch an image from an API and sets it as the wallpaper. The user doesn't really need to open the app for this to function. So, a GPlay Services or an app update removing the jobs I schedule with break the app, I think. Do you think I can work my way around this problem?

**Comment by LouisCAD** [comment] 2016-10-19 06:13
On [this page](https://developers.google.com/cloud-messaging/network-manager#run_tasks), it's written that Google Play Services has an `onInitializeTasks()` callback called after Play Services or the client app is updated, where we are supposed to reschedule tasks. It's not ideal as not having to reschedule tasks would be better, but how can we apply this "workaround" to Firebase Job Dispatcher in the meantime?

**Comment by trignodev-manish** [comment] 2016-12-19 11:20
is this an issue with recurring job only or with one time scheduled job also, i have used this in my project and wondering if this is happening in one time scheduled job as well then that will create issues and i have to look for alternates.

**Comment by LouisCAD** [comment] 2017-02-07 19:53
**When this critical issue will see a fix?**

I'm going to advocate against this library if usability issues big like this one take months (closer to a year in fact) to be solved here!

**Comment by sytolk** [comment] 2017-02-27 12:42
@ciarand Do you know how jobs can be rescheduled here ?
https://github.com/sytolk/firebase-jobdispatcher-android/commit/a47ab5a440e72eeeee307fe781e7d06d88960acc

**Comment by wilburt** [comment] 2017-03-02 21:47
Has this issue been fixed yet?

**Comment by summersmichael** [comment] 2017-04-06 21:13
If anyone is still facing this issue, a workaround I found is what LouisCAD touched on. Create a stub GcmTaskService, that does nothing in OnRunTask, and override OnInitializeTasks function to perform all re-scheduling.

**Comment by aftabsikander** [comment] 2017-06-07 15:35
@summersmichael  any example code you can share?

**Comment by wilburt** [comment] 2017-06-07 17:18
@aftabsikander here:

```
public class PostNotifyReschedule extends GcmTaskService {
    @Override
    public int onRunTask(TaskParams taskParams) {
        PostNotification.switchOn(PostNotifyReschedule.this);  // Schedules the job
        return 0;
    }
}

```
Then register it in the manifest as usual:

```
<service
            android:name=".services.PostNotifyReschedule"
            android:enabled="true"
            android:exported="true"
            android:permission="com.google.android.gms.permission.BIND_NETWORK_TASK_SERVICE">
            <intent-filter>
                <action android:name="com.google.android.gms.gcm.ACTION_TASK_READY" />
            </intent-filter>

 </service>
```

**Comment by lpellegr** [comment] 2017-06-25 16:34
@ciarand @SUPERCILEX @ogeidix @googolmo @jenzz @michaeldiener @vRallev ping

**Comment by unEgor** [comment] 2017-07-22 01:26
As a workaround you could listen to  [ACTION_MY_PACKAGE_REPLACED](https://developer.android.com/reference/android/content/Intent.html#ACTION_MY_PACKAGE_REPLACED) and reschedule your job onReceive.

**Comment by LouisCAD** [comment] 2017-08-23 15:47
@ciarand I'm ringing the bell. What's the progress on your internal issue on this?
It's been more than a year, 3 newer Android versions since (7.0, 7.1, 8.0).
Are we waiting for something, or are we waiting for vaporware?

**Comment by LouisCAD** [comment] 2017-08-23 15:55
@ciarand Also, why is this issue marked as unassigned?

**Comment by LouisCAD** [comment] 2017-08-28 09:06
Hi,
After making a small sample to try the behavior of this library, I could see that jobs are not forgotten after an app update or Google Play Services update (downgraded to stock v8 too see how the sample would behave when auto updating to v11). So it seems this issue is fixed and that Firebase Job Dispatcher doesn't need the trick that was needed for GCMTaskManager after all. So why is this issue still open?

**Comment by LouisCAD** [comment] 2017-09-09 14:44
Hi,
After testing again, I saw a scheduled job that wasn't run after I updated my app through adb with Android Studio, so this critical issue (as seen from us, developers who want to make reliable apps that user can trust, at least) seems to still be unresolved. I'll publish a gist with my workaround until the folks that work on this library fix this issue.

**Comment by LouisCAD** [comment] 2017-09-09 15:07
[Here's a workaround](https://gist.github.com/LouisCAD/ea7228360250b34d8da4668768018839)

**Comment by ciarand** [comment] 2017-09-19 21:21
That makes sense, @LouisCAD. The current version of Google Play services does not cancel FJD jobs when the app is updated, which matches the behavior of the platform job scheduler. There was a bug in older versions where it would, but it was fixed in the February release (v9). We were waiting for market penetration before closing this, but it ended up falling off our radar.

If the onInitializeTasks behavior + pre-v9 compat is important, it's probably much easier just to listen for your MY_PACKAGE_REPLACED broadcast instead of the onInitializeTasks, no? That saves you the hassle of including the GCM package and is ultimately a better solution from the system's perspective.

**Comment by LouisCAD** [comment] 2017-09-20 07:27
@ciarand Thanks for letting us know the status of this issue! We had really no information about this before.
Doesn't `MY_PACKAGE_REPLACED` fails to be called when Google Play Services themselves are replaced (and discard scheduled jobs before v9)?
Also, maybe a solution is to block our app from working until Play Services are updated to v9+, using [a simple check like this one](https://stackoverflow.com/a/22219029/4433326)?

**Comment by samtstern** [comment] 2018-01-23 21:42
@ciarand do you consider this closed?

**Comment by Signez** [comment] 2018-10-16 15:21
> There was a bug in older versions where it would, but it was fixed in the February release (v9). We were waiting for market penetration before closing this, but it ended up falling off our radar.

Is the market penetration good enough now (in October 2018) to consider that problem solved? I'm considering using Firebase JobDispatcher and the workaround is non-trivial.

**Comment by samtstern** [comment] 2020-04-07 21:05
In April 2019 we announced that Firebase Job Dispatcher would be deprecated today, April 7th 2020.  For this reason we are going to close all open issues and archive the repository.  We will also stop supporting FJD for new app installations (such as those targeting sdk versions greater than Android Q).  Existing apps that rely on FJD should continue to function as usual.

While we will no longer work on FJD, we encourage you to [migrate to Work Manager](https://developer.android.com/topic/libraries/architecture/workmanager/migrating-fb) which is a superior tool and fully supported by the Android team.

Thank you for taking the time to try the library and provide this feedback.  We sincerely appreciate your effort and we apologize for not addressing it in time.

**Closed by samtstern** 2020-04-07 21:05 UTC
