### ISSUE TITLE
Job did not start even after meeting all the constraints

### ISSUE THREAD

**Issue by vivekmd** [firebase/firebase-jobdispatcher-android#147] opened 2017-09-02 08:12 UTC
This is my job
Job updateJob = dispatcher.newJobBuilder()
                .setService(UpdateJobService.class)
                .setTag(trackingNumber)
                .setReplaceCurrent(true)
                .setLifetime(Lifetime.FOREVER)
                .setRetryStrategy(RetryStrategy.DEFAULT_LINEAR)
                .setConstraints(Constraint.ON_ANY_NETWORK)
                .setTrigger(Trigger.NOW)
                .build();

Scheduled around 30 jobs when offline and came back online. Some of the jobs (around 4-5) got executed but the rest got stuck.
Checked status with adb shell dumpsys activity service GcmService.
Jobs were stuck with status READY_NO_SPACE.

PFB gcmservice dump for one of the stuck jobs :
(scheduled) com.myn.deliveryapp/com.firebase.jobdispatcher.GooglePlayReceiver{u=0 tag="ML0000890853" trigger=window{start=0s,end=30s,earliest=-120s,latest=-90s} requirements=[NET_CONNECTED] attributes=[PERSISTED] scheduled=-120s last_run=N/A jid=N/A status=READY_NO_SPACE retries=0}
Not yet run.

**Comment by unEgor** [comment] 2017-09-02 12:40
Thank you for reporting.
The fix will be released with next version of google play services.
All your jobs will be executed eventually with arbitrary delay.

**Closed by unEgor** 2017-09-02 12:40 UTC

**Comment by vivekmd** [comment] 2017-09-02 16:15
What if jobs have to be executed immediately network is available? Is firebase jobdispatcher not the right scheduler in that case ?

**Comment by unEgor** [comment] 2017-09-05 21:27
The arbitrary delay is caused by a bug in google play service.

FJD is the right scheduler for the use case.
