### ISSUE TITLE
Crash: NullPointerException in JobService.start

### ISSUE THREAD

**Issue by summersmichael** [firebase/firebase-jobdispatcher-android#104] opened 2017-03-31 17:42 UTC
Using `com.firebase:firebase-jobdispatcher-with-gcm-dep:0.5.0` dependency in my project.

In Firebase, I am seeing multiple crashes being reported for JobService.start method (Line 110).

Here is the stacktrace being reported:

```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void com.firebase.jobdispatcher.q$a.a(int)' on a null object reference
com.firebase.jobdispatcher.JobService.start (JobService.java:110)
com.firebase.jobdispatcher.ExternalReceiver$JobServiceConnection.onServiceConnected (ExternalReceiver.java:164)
android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java:1339)
android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java:1356)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:7325)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

This is the line of code in question:
` runningJobs.remove(job.getTag()).sendResult(RESULT_SUCCESS);`

There are no null checks before executing this line. And since this method is final and not public, our subclass cannot override and wrap a super call in a try/catch. 

Please fix or let me know of a workaround.

Thanks!

**Comment by unEgor** [comment] 2017-03-31 18:02
Hi Michael,

Do you call JobService#jobFinished in JobService#onStartJob ?
If not it might be a race condition that was fixed in https://github.com/firebase/firebase-jobdispatcher-android/pull/102

You should not call JobService#jobFinished in JobService#onStartJob

**Comment by unEgor** [comment] 2017-03-31 18:08
Let me know if the issue is still reproducible.

**Comment by summersmichael** [comment] 2017-03-31 18:38
Thanks for the quick response. As a matter of fact, I was calling JobService#jobFinished in JobService#onStartJob! I will remove this call for the next release and see if it fixes the issue. Unfortunately I cannot test the fix myself. I haven't been able to reproduce; it's quite a rare occurrence (out of thousands of users, only a handful have faced the issue). 

So, since I was misusing this method, when and where is it proper to use? The [documentation](https://developer.android.com/reference/android/app/job/JobService.html) gave me the impression that it should be called when you're done with all work in JobService#onStartJob.

**Comment by unEgor** [comment] 2017-03-31 20:45
You need to call JobService#jobFinished only if  "true" was returned from JobService#onStartJob. Which means that you started separate thread for the job.
And at the end of the job you need to call JobService#jobFinished to notify that it is completed.

If onStartJob you return "false" it means that your Job was completed(no more work).

**Comment by unEgor** [comment] 2017-04-01 06:04
I was wrong. It should be possible to call jobFinished on main thread during onStartJob.
I'll fix the NPE and update javadocs.
Sorry for the confusion.

**Comment by unEgor** [comment] 2017-04-04 00:35
It is fixed now by https://github.com/firebase/firebase-jobdispatcher-android/pull/105

**Closed** 2017-05-04 01:10 UTC

**Comment by vit001** [comment] 2017-05-21 23:25
I am experiencing this issue in 0.6.0. Please advise.
