### ISSUE TITLE
When I can lauch the job one a day ?

### ISSUE THREAD

**Issue by Paul75** [firebase/firebase-jobdispatcher-android#184] opened 2017-11-11 09:17 UTC
Hello,

When I can start job one a day in an hour have given ? Exemple : stall all day at 7' PM ?

Thanks

**Comment by Paul75** [comment] 2017-11-14 14:06
Nobody ?

**Comment by jplazcano87** [comment] 2017-11-14 15:40
did you find a way ? @Paul75

**Comment by Paul75** [comment] 2017-11-14 15:42
no ....

**Comment by jplazcano87** [comment] 2017-11-14 16:00
i find that the only way to perform an exact job is using an AlarmManager, this API is not deprecated in android Oreo, but the official docs warns you about heavy battery usage. this is a little bit messy because works in combination with a Broadcast receiver to perform the actual task

**Comment by Paul75** [comment] 2017-11-14 16:01
And When I can implement them ?

**Comment by lordplagus02** [comment] 2017-11-14 22:00
I think this is possibly a duplicate of [this issue](https://github.com/firebase/firebase-jobdispatcher-android/issues/52).

**Comment by samtstern** [comment] 2018-01-23 21:43
Agree with @lordplagus02 and @jplazcano87.  This is a duplicate of #52.  If the answers in that thread don't work for you and you truly need exact time scheduling, use `AlarmManager`.

**Closed by samtstern** 2018-01-23 21:43 UTC
